### PR TITLE
Testing Issues Fixed

### PR DESCRIPTION
**Pull request by slpriya**
[x] Fixed for Delete comment, 
[x] FIxed the Profile validation error
[x] Added comment body is required=ture in posts model
[x] In follows.js Replaced user_id of req.params to userId
[x]. changes in the comment error message
[x] Change Password Validation issue fixed

### CODE REVIEW

**Review by Emily484 — COMMENTED** [review]
Is this right: "commentBody: { type: String, required: true }," shouldn't it be false, comments are not required?

**Comment by slpriya** [comment]
> Is this right: "commentBody: { type: String, required: true }," shouldn't it be false, comments are not required?

For post comments, comments are required if not what will you comment? what will u send to back end when u click add comment

**Comment by slpriya** [comment]
there is only field in comment section is commentBody

**Comment by slpriya** [comment]
> Is this right: "commentBody: { type: String, required: true }," shouldn't it be false, comments are not required?

CommentBody is not required for the post. But CommentBody is required to post comments.

**Review by solongoch — APPROVED** [review]
Good to merge

**Review by Emily484 — APPROVED** [review]
looks good

**Comment by slpriya** [comment]
[x] Fixed for Delete comment,
[x] FIxed the Profile validation error
[x] Added comment body is required=ture in posts model
[x] In follows.js Replaced user_id of req.params to userId
[x]. changes in the comment error message
[x] Change Password Validation issue fixed

**Pull request merged**
