### PR TITLE
login validation

### PR DESCRIPTION
**Pull request by Emily484**

### CODE REVIEW

**Review by solongoch — APPROVED** [review]

**Review by Emily484 — COMMENTED** [review]
Thank you

**Review by slpriya — APPROVED** [review]

**Review by Emily484 — COMMENTED** [review]
thank you

**Review by Emily484 — COMMENTED** [review]
ok

**Review by Emily484 — COMMENTED** [review]
reviwed

**Review by Emily484 — COMMENTED** [review]
reviewed

**Pull request closed without merging**
